import 'dart:core';
import 'dart:io';

import 'package:editable/editable.dart';
import 'package:fl_chart/fl_chart.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_linkify/flutter_linkify.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:get/get.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:intl/intl.dart';
import 'package:my_physical_therapist_admin/configs/configs.dart';
import 'package:my_physical_therapist_admin/configs/my_physical_therapist_icons.dart';
import 'package:my_physical_therapist_admin/models/model.dart';
import 'package:my_physical_therapist_admin/views/widgets/widget.dart';
import 'package:my_physical_therapist_admin/providers/provider.dart';
import 'package:photo_view/photo_view.dart';
import 'package:table_calendar/table_calendar.dart';
import 'package:datetime_picker_formfield/datetime_picker_formfield.dart';
import 'package:image_picker/image_picker.dart';

part "auth/auth_page.dart";
part "auth/sign_in_page.dart";
part "auth/sign_up_page.dart";
part "auth/forgot_password_page.dart";
part 'app/landing_page.dart';
part 'app/event_page.dart';
part 'app/main-admin/user_admin_list_page.dart';
part 'app/regular-admin/user_homepage.dart';
part 'app/regular-admin/user_default_page.dart';
part 'app/regular-admin/user_patient_education_page.dart';
part 'app/regular-admin/user_goal_page.dart';
// part 'app/goal_page.dart';
part 'app/regular-admin/exercises_goal_page.dart';
part 'app/regular-admin/weight_tracker_page.dart';
part 'app/regular-admin/pain_scale_page.dart';
// part 'app/chat_page.dart';
// part 'app/exercises_page.dart';
part 'subpage/main-admin/user_list.dart';
part 'subpage/main-admin/admin_list.dart';
part 'subpage/regular-admin/patient_education_subpage.dart';
part 'subpage/regular-admin/exercises_goal_detailed_page.dart';
part 'subpage/regular-admin/editables_page.dart';
part 'subpage/event_item_page.dart';
part 'subpage/event_editor.dart';
// part 'sub_page/chat_contact_page.dart';