/// Flutter icons MyPhysicalTherapist
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyPhysicalTherapist
///      fonts:
///       - asset: fonts/MyPhysicalTherapist.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyPhysicalTherapist {
  MyPhysicalTherapist._();

  static const _kFontFam = 'MyPhysicalTherapist';
  static const String? _kFontPkg = null;

  static const IconData barbell_outlined = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData meal = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pain = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vector = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData barbell_filled = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doc = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
